name: Osibusi Full 7/24 Otomatik

on:
  schedule:
    - cron: "0 */3 * * *"  # Her 3 saatte bir
  workflow_dispatch: # Manuel tetikleme

jobs:
  run-osibusi:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Script 15 dk'dan uzun sürerse abort

    steps:
      # 1️⃣ Repo'yu klonla
      - name: Repo'yu Klonla
        uses: actions/checkout@v4

      # 2️⃣ Python kur
      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # 3️⃣ Playwright ve bağımlılıkları kur
      - name: Playwright ve Bağımlılıkları Kur
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests playwright
          playwright install chromium

      # 4️⃣ Script'i çalıştır
      - name: birazf
