name: Osibusi Full Otomatik 0510

on:
  schedule:
    - cron: "0 */3 * * *" # Her 3 saatte bir
  workflow_dispatch:

jobs:
  run-osibusi:
    runs-on: ubuntu-latest
    steps:
      - name: Repo'yu Klonla
        uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Python Bağımlılıkları Kur
        run: |
          pip install --upgrade pip
          pip install playwright
          playwright install chromium

      - name: birazyedek_full.py Çalıştır
        run: |
          python birazyedek_full.py

      - name: Değişiklikleri Git'e Ekle ve Push Et
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add M3U/Osibusibirazfull.m3u
          git commit -m "Otomatik güncelleme: $(date '+%Y-%m-%d %H:%M:%S')" || echo "Değişiklik yok"
          git pull --rebase
          git push origin main
