name: Osibusi Full All Channels

on:
  schedule:
    - cron: "0 */3 * * *" # Her 3 saatte bir
  workflow_dispatch:

jobs:
  run-osibusi:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu Klonla
        uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Bağımlılıkları Kur
        run: |
          pip install --upgrade pip
          pip install playwright requests
          playwright install chromium

      - name: Script'i Çalıştır
        run: |
          python birazfull_final_allchannels.py

      - name: Değişiklikleri Git'e Ekle ve Push Et
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # Remote branch'teki güncel değişiklikleri al
          git pull --rebase origin main || echo "Pull başarısız, devam ediliyor."
          # M3U dosyasını ekle ve commit yap
          git add M3U/Osibusibirazfull.m3u
          git commit -m "Otomatik güncelleme: $(date '+%Y-%m-%d %H:%M:%S')" || echo "Değişiklik yok"
          # Push işlemi
          git push origin main
