name: Osibusi IPTV Otomatik

on:
  schedule:
    - cron: "0 */3 * * *" # Her 3 saatte bir
  workflow_dispatch: # Manuel çalıştırma

jobs:
  run-osibusi:
    runs-on: ubuntu-latest
    steps:
      - name: Repo'yu Klonla
        uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Bağımlılıkları Kur
        run: |
          pip install requests

      - name: OSIBUSI Script Çalıştır
        run: |
          python osibusi.py

     - name: Playlist'i Commit Et
  run: |
    if [ -f "OSIBUSITRGOALSS.m3u" ]; then
      git config --global user.name "github-actions[bot]"
      git config --global user.email "github-actions[bot]@users.noreply.github.com"

      git pull --rebase origin main

      git add OSIBUSITRGOALSS.m3u
      git commit -m "Otomatik güncelleme: $(date '+%Y-%m-%d %H:%M:%S')" || echo "Değişiklik yok"
      git push
    else
      echo "Playlist dosyası bulunamadı, commit atlanıyor."
    fi
