name: Osibusi Full biraz playwright  Otomatik

on:
  schedule:
    - cron: "0 */3 * * *" # Her 3 saatte bir
  workflow_dispatch:

jobs:
  run-osibusi:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Repo'yu klonla
      - name: Repo'yu Klonla
        uses: actions/checkout@v4

      # 2️⃣ Python kur
      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # 3️⃣ Playwright ve bağımlılıkları kur
      - name: Playwright ve Python Bağımlılıkları Kur
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests playwright
          playwright install

      # 4️⃣ Script'i çalıştır
      - name: birazfull_playwright.py Çalıştır
        run: python birazfull_playwright.py

      # 5️⃣ Değişiklikleri git'e ekle ve push et
      - name: Değişiklikleri Git'e Ekle ve Push Et
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add M3U/Osibusibirazfull.m3u
          git commit -m "Otomatik güncelleme: $(date '+%Y-%m-%d %H:%M:%S')" || echo "Değişiklik yok"
          git push origin main
